"""initial schema v1.1 (21 tables)

Revision ID: 56231556727b
Revises:
Create Date: 2026-09-09 14:09:15.489429
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56231556727b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "membership_grades",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "training_institutions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("institution_code", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("business_registration_no", sa.String(length=50), nullable=True),
        sa.Column("contact_name", sa.String(length=100), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ci_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ci_hash"),
    )
    op.create_table(
        "admin_allowed_emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("joined_admin_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["admin_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["joined_admin_id"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_admin_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_admin_id"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_actor_created_at",
        "audit_logs",
        ["actor_admin_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "certificate_pricing_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("membership_grade_id", sa.Uuid(), nullable=False),
        sa.Column("issue_type", sa.String(length=30), nullable=False),
        sa.Column("price_krw", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_grade_id"],
            ["membership_grades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cpr_grade_type_valid_from",
        "certificate_pricing_rules",
        ["membership_grade_id", "issue_type", "valid_from"],
        unique=False,
    )
    op.create_table(
        "identity_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_verification_id", sa.String(length=255), nullable=True),
        sa.Column("redirect_state_hash", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("verified_name", sa.String(length=100), nullable=True),
        sa.Column("verified_phone_encrypted", sa.Text(), nullable=True),
        sa.Column("ci_hash", sa.String(length=255), nullable=True),
        sa.Column("di_hash", sa.String(length=255), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_verification_id"),
    )
    op.create_index(
        "ix_idv_ci_hash", "identity_verifications", ["ci_hash"], unique=False
    )
    op.create_index("ix_idv_status", "identity_verifications", ["status"], unique=False)
    op.create_index(
        "ix_idv_user_created_at",
        "identity_verifications",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trainees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("trainee_no", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone_encrypted", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("membership_grade_id", sa.Uuid(), nullable=True),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_grade_id"], ["membership_grades.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trainee_no"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        "ix_trainees_membership_grade_id",
        "trainees",
        ["membership_grade_id"],
        unique=False,
    )
    op.create_index("ix_trainees_name", "trainees", ["name"], unique=False)
    op.create_index(
        "ix_trainees_review_status", "trainees", ["review_status"], unique=False
    )
    op.create_table(
        "training_courses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_code", sa.String(length=100), nullable=True),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["training_institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_code"),
    )
    op.create_index(
        "ix_courses_institution_id",
        "training_courses",
        ["institution_id"],
        unique=False,
    )
    op.create_index("ix_courses_name", "training_courses", ["name"], unique=False)
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "identity_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("identity_verification_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("matched_by", sa.String(length=30), nullable=True),
        sa.Column("determined_grade_id", sa.Uuid(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["determined_grade_id"], ["membership_grades.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["identity_verification_id"],
            ["identity_verifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["trainee_id"], ["trainees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_idr_status", "identity_reviews", ["status"], unique=False)
    op.create_index(
        "ix_idr_trainee_id", "identity_reviews", ["trainee_id"], unique=False
    )
    op.create_index(
        "ix_idr_user_created_at",
        "identity_reviews",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "trainee_grade_histories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=False),
        sa.Column("previous_grade_id", sa.Uuid(), nullable=True),
        sa.Column("new_grade_id", sa.Uuid(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["new_grade_id"], ["membership_grades.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["previous_grade_id"], ["membership_grades.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["trainees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_tgh_trainee_changed_at",
        "trainee_grade_histories",
        ["trainee_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "training_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("training_record_no", sa.String(length=100), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("institution_id", sa.Uuid(), nullable=True),
        sa.Column("course_name", sa.String(length=255), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column("total_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("completed_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("evidence_file_key", sa.Text(), nullable=True),
        sa.Column("completion_status", sa.String(length=30), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["training_courses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"], ["training_institutions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["trainees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("training_record_no"),
    )
    op.create_index(
        "ix_records_completion_status",
        "training_records",
        ["completion_status"],
        unique=False,
    )
    op.create_index(
        "ix_records_course_id", "training_records", ["course_id"], unique=False
    )
    op.create_index(
        "ix_records_institution_id",
        "training_records",
        ["institution_id"],
        unique=False,
    )
    op.create_index("ix_records_source", "training_records", ["source"], unique=False)
    op.create_index(
        "ix_records_trainee_ended_at",
        "training_records",
        ["trainee_id", "ended_at"],
        unique=False,
    )
    op.create_table(
        "certificate_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_no", sa.String(length=100), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=False),
        sa.Column("training_record_id", sa.Uuid(), nullable=False),
        sa.Column("previous_certificate_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("issue_type", sa.String(length=30), nullable=False),
        sa.Column("membership_grade_id", sa.Uuid(), nullable=False),
        sa.Column("pricing_rule_id", sa.Uuid(), nullable=True),
        sa.Column("amount_krw", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["membership_grade_id"],
            ["membership_grades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"], ["certificate_pricing_rules.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["trainees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_record_id"],
            ["training_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_no"),
    )
    op.create_index("ix_creq_status", "certificate_requests", ["status"], unique=False)
    op.create_index(
        "ix_creq_trainee_requested_at",
        "certificate_requests",
        ["trainee_id", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_creq_training_record_id",
        "certificate_requests",
        ["training_record_id"],
        unique=False,
    )
    op.create_table(
        "payment_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_no", sa.String(length=100), nullable=False),
        sa.Column("certificate_request_id", sa.Uuid(), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=False),
        sa.Column("amount_krw", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["certificate_request_id"],
            ["certificate_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["trainees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("certificate_request_id"),
        sa.UniqueConstraint("order_no"),
    )
    op.create_index("ix_po_status", "payment_orders", ["status"], unique=False)
    op.create_index(
        "ix_po_trainee_created_at",
        "payment_orders",
        ["trainee_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "certificates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("certificate_no", sa.String(length=100), nullable=False),
        sa.Column("certificate_request_id", sa.Uuid(), nullable=False),
        sa.Column("trainee_id", sa.Uuid(), nullable=False),
        sa.Column("training_record_id", sa.Uuid(), nullable=False),
        sa.Column("payment_order_id", sa.Uuid(), nullable=True),
        sa.Column("issued_name", sa.String(length=100), nullable=False),
        sa.Column("course_name", sa.String(length=255), nullable=False),
        sa.Column("institution_name", sa.String(length=255), nullable=False),
        sa.Column("total_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("completed_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("training_started_at", sa.Date(), nullable=True),
        sa.Column("training_ended_at", sa.Date(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("pdf_file_key", sa.Text(), nullable=True),
        sa.Column("pdf_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["certificate_request_id"],
            ["certificate_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_order_id"], ["payment_orders.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["trainees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_record_id"],
            ["training_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("certificate_no"),
        sa.UniqueConstraint("certificate_request_id"),
    )
    op.create_index(
        "ix_cert_no_issued_at",
        "certificates",
        ["certificate_no", "issued_at"],
        unique=False,
    )
    op.create_index(
        "ix_cert_record_issued_at",
        "certificates",
        ["training_record_id", "issued_at"],
        unique=False,
    )
    op.create_index(
        "ix_cert_trainee_issued_at",
        "certificates",
        ["trainee_id", "issued_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_creq_previous_certificate",
        "certificate_requests",
        "certificates",
        ["previous_certificate_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_order_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=True),
        sa.Column("merchant_payment_id", sa.String(length=255), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_amount_krw", sa.Integer(), nullable=False),
        sa.Column("paid_amount_krw", sa.Integer(), nullable=False),
        sa.Column("receipt_url", sa.Text(), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_order_id"], ["payment_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "payment_order_id", "attempt_no", name="uq_attempts_order_no"
        ),
        sa.UniqueConstraint("provider_payment_id"),
    )
    op.create_index(
        "ix_attempts_status_created_at",
        "payment_attempts",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "certificate_verification_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("certificate_id", sa.Uuid(), nullable=True),
        sa.Column("input_certificate_no", sa.String(length=100), nullable=False),
        sa.Column("input_issue_date", sa.Date(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("requester_ip_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"], ["certificates.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cvl_certificate_verified_at",
        "certificate_verification_logs",
        ["certificate_id", "verified_at"],
        unique=False,
    )
    op.create_table(
        "payment_refunds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("payment_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("provider_refund_id", sa.String(length=255), nullable=True),
        sa.Column("amount_krw", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["payment_attempt_id"], ["payment_attempts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_refund_id"),
    )
    op.create_table(
        "payment_webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=True),
        sa.Column("payment_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processing_status", sa.String(length=30), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payment_attempt_id"], ["payment_attempts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_webhook_provider_event"
        ),
    )
    op.create_index(
        "ix_webhook_payment_attempt_id",
        "payment_webhook_events",
        ["payment_attempt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_webhook_payment_attempt_id", table_name="payment_webhook_events")
    op.drop_table("payment_webhook_events")
    op.drop_table("payment_refunds")
    op.drop_index(
        "ix_cvl_certificate_verified_at", table_name="certificate_verification_logs"
    )
    op.drop_table("certificate_verification_logs")
    op.drop_index("ix_attempts_status_created_at", table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index("ix_cert_trainee_issued_at", table_name="certificates")
    op.drop_index("ix_cert_record_issued_at", table_name="certificates")
    op.drop_index("ix_cert_no_issued_at", table_name="certificates")
    op.drop_table("certificates")
    op.drop_index("ix_po_trainee_created_at", table_name="payment_orders")
    op.drop_index("ix_po_status", table_name="payment_orders")
    op.drop_table("payment_orders")
    op.drop_index("ix_creq_training_record_id", table_name="certificate_requests")
    op.drop_index("ix_creq_trainee_requested_at", table_name="certificate_requests")
    op.drop_index("ix_creq_status", table_name="certificate_requests")
    op.drop_table("certificate_requests")
    op.drop_index("ix_records_trainee_ended_at", table_name="training_records")
    op.drop_index("ix_records_source", table_name="training_records")
    op.drop_index("ix_records_institution_id", table_name="training_records")
    op.drop_index("ix_records_course_id", table_name="training_records")
    op.drop_index("ix_records_completion_status", table_name="training_records")
    op.drop_table("training_records")
    op.drop_index("ix_tgh_trainee_changed_at", table_name="trainee_grade_histories")
    op.drop_table("trainee_grade_histories")
    op.drop_index("ix_idr_user_created_at", table_name="identity_reviews")
    op.drop_index("ix_idr_trainee_id", table_name="identity_reviews")
    op.drop_index("ix_idr_status", table_name="identity_reviews")
    op.drop_table("identity_reviews")
    op.drop_table("user_sessions")
    op.drop_index("ix_courses_name", table_name="training_courses")
    op.drop_index("ix_courses_institution_id", table_name="training_courses")
    op.drop_table("training_courses")
    op.drop_index("ix_trainees_review_status", table_name="trainees")
    op.drop_index("ix_trainees_name", table_name="trainees")
    op.drop_index("ix_trainees_membership_grade_id", table_name="trainees")
    op.drop_table("trainees")
    op.drop_index("ix_idv_user_created_at", table_name="identity_verifications")
    op.drop_index("ix_idv_status", table_name="identity_verifications")
    op.drop_index("ix_idv_ci_hash", table_name="identity_verifications")
    op.drop_table("identity_verifications")
    op.drop_index(
        "ix_cpr_grade_type_valid_from", table_name="certificate_pricing_rules"
    )
    op.drop_table("certificate_pricing_rules")
    op.drop_index("ix_audit_entity", table_name="audit_logs")
    op.drop_index("ix_audit_actor_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("admin_allowed_emails")
    op.drop_table("users")
    op.drop_table("training_institutions")
    op.drop_table("membership_grades")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
