import type { Course, Institution } from '../model/institution'

/**
 * 교육기관·과정 마스터 목업. 교육이력(rcd-00x)이 이 id를 참조한다.
 * USE_MOCK 동안 등록·수정이 배열을 직접 갱신한다.
 */
export const MOCK_INSTITUTIONS: Institution[] = [
  {
    id: 'ins-001',
    name: '협회 본부',
    institutionCode: 'HQ',
    isActive: true,
    createdAt: '2026-01-02T09:00:00',
  },
  {
    id: 'ins-002',
    name: '부산지회',
    institutionCode: 'BSN',
    isActive: true,
    createdAt: '2026-01-02T09:05:00',
  },
  {
    id: 'ins-003',
    name: '서울지회',
    institutionCode: 'SEL',
    isActive: true,
    createdAt: '2026-01-02T09:10:00',
  },
  {
    id: 'ins-004',
    name: '대구지회',
    institutionCode: 'DAE',
    isActive: false,
    createdAt: '2026-01-02T09:15:00',
  },
]

export const MOCK_COURSES: Course[] = [
  {
    id: 'crs-001',
    institutionId: 'ins-001',
    institutionName: '협회 본부',
    name: '비파괴검사 계속교육 (정기)',
    courseCode: 'NDT-101',
    description: '정기 계속교육 — 비파괴검사 분야',
    totalHours: 8,
    category: '계속교육',
    isActive: true,
    createdAt: '2026-01-03T09:00:00',
  },
  {
    id: 'crs-002',
    institutionId: 'ins-002',
    institutionName: '부산지회',
    name: '감리원 법정 계속교육 2차',
    courseCode: 'SUP-201',
    description: '감리원 법정 의무 교육',
    totalHours: 16,
    category: '법정교육',
    isActive: true,
    createdAt: '2026-01-03T09:10:00',
  },
  {
    id: 'crs-003',
    institutionId: 'ins-003',
    institutionName: '서울지회',
    name: '건설기술 계속교육 (온라인)',
    courseCode: 'CON-110',
    description: '온라인 계속교육',
    totalHours: 4,
    category: '계속교육',
    isActive: true,
    createdAt: '2026-01-03T09:20:00',
  },
  {
    id: 'crs-004',
    institutionId: 'ins-001',
    institutionName: '협회 본부',
    name: '설비공사 감리 실무협의',
    courseCode: 'FAC-210',
    description: '설비 분야 실무 협의체 교육',
    totalHours: 8,
    category: '실무교육',
    isActive: true,
    createdAt: '2026-01-03T09:30:00',
  },
  {
    id: 'crs-005',
    institutionId: 'ins-004',
    institutionName: '대구지회',
    name: '토목 안전관리 세미나',
    courseCode: 'CIV-130',
    description: '토목 분야 안전 세미나',
    totalHours: 4,
    category: '세미나',
    isActive: true,
    createdAt: '2026-01-03T09:40:00',
  },
  {
    id: 'crs-006',
    institutionId: 'ins-002',
    institutionName: '부산지회',
    name: '환경 영향 평가 교육',
    courseCode: 'ENV-140',
    description: '환경 영향 평가 기초',
    totalHours: 8,
    category: '계속교육',
    isActive: false,
    createdAt: '2026-01-03T09:50:00',
  },
]
