export * from './model/institution'
export { institutionQueries, courseQueries, sessionNameQueries } from './api/institution-queries'
export { getInstitutionList } from './api/get-institution-list'
export { postInstitution } from './api/post-institution'
export { patchInstitution } from './api/patch-institution'
export { getCourseList, getCourseCategories } from './api/get-course-list'
export { getCourseDetail } from './api/get-course-detail'
export { postCourse } from './api/post-course'
export { patchCourse } from './api/patch-course'
export { deleteInstitution } from './api/delete-institution'
export { deleteCourse } from './api/delete-course'
export { getSessionNameList } from './api/get-session-name-list'
export { postSessionName } from './api/post-session-name'
export { patchSessionName } from './api/patch-session-name'
export { deleteSessionName } from './api/delete-session-name'
export type { InstitutionListQuery, CourseListQuery, SessionNameListQuery } from './api/query/institution-list-query'
