export * from './model/institution'
export { institutionQueries, courseQueries } from './api/institution-queries'
export { getInstitutionList } from './api/get-institution-list'
export { postInstitution } from './api/post-institution'
export { patchInstitution } from './api/patch-institution'
export { getCourseList } from './api/get-course-list'
export { postCourse } from './api/post-course'
export { patchCourse } from './api/patch-course'
export type { InstitutionListQuery, CourseListQuery } from './api/query/institution-list-query'
