import type { AuditLog } from '../model/audit-log'

/** 감사로그 목업 — mutation 기록은 미반영 (정적 표본) */
export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    actorAdminId: 'adm-001',
    actorName: '김관리',
    action: 'identity_review.approve',
    entityType: 'identity_review',
    entityId: 'idr-001',
    before: { status: 'pending' },
    after: { status: 'approved' },
    createdAt: '2026-03-02T14:20:00',
  },
  {
    id: 'aud-002',
    actorAdminId: 'adm-001',
    actorName: '김관리',
    action: 'certificate.revoke',
    entityType: 'certificate',
    entityId: 'crt-003',
    before: { status: 'issued' },
    after: { status: 'revoked' },
    createdAt: '2026-08-11T10:05:00',
  },
  {
    id: 'aud-003',
    actorAdminId: 'adm-002',
    actorName: '박실무',
    action: 'pricing_rule.create',
    entityType: 'pricing_rule',
    entityId: 'prc-002',
    before: null,
    after: { price_krw: 1000, issue_type: 'reissue' },
    createdAt: '2026-08-12T15:30:00',
  },
  {
    id: 'aud-004',
    actorAdminId: 'adm-001',
    actorName: '김관리',
    action: 'trainee.update',
    entityType: 'trainee',
    entityId: 'tr-002',
    before: { memo: null },
    after: { memo: '2026년 자격 갱신 예정' },
    createdAt: '2026-08-13T09:12:00',
  },
  {
    id: 'aud-005',
    actorAdminId: 'adm-002',
    actorName: '박실무',
    action: 'payment.refund',
    entityType: 'payment_order',
    entityId: 'pay-003',
    before: { status: 'paid' },
    after: { status: 'refunded' },
    createdAt: '2026-08-14T11:47:00',
  },
]
