export * from './model/training-record'
export { trainingRecordQueries } from './api/training-record-queries'
export { getTrainingRecordList } from './api/get-training-record-list'
export { getTrainingRecordDetail } from './api/get-training-record-detail'
export { postTrainingRecord } from './api/post-training-record'
export { patchTrainingRecord } from './api/patch-training-record'
export { deleteTrainingRecord } from './api/delete-training-record'
export type { TrainingRecordListQuery } from './api/query/training-record-list-query'
